apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world-container
          image: your-docker-image
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: <RDS-ENDPOINT-HERE>
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: password
