apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: hello-world-cluster
  region: us-east-2
vpc:
  cidr: "10.0.0.0/16"
  subnets:
    private:
      us-east-2a: { cidr: "10.0.1.0/24" }
      us-east-2b: { cidr: "10.0.2.0/24" }
nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    ssh:
      allow: true
      publicKeyName: k8s-test
